### PR TITLE
Support for `trybuild` and similar macro testing tools

### PR DESCRIPTION
**Pull request by neysofu**
https://github.com/dtolnay/trybuild is a Rust testing utility that invokes `rustc` on user-provided source files and tests whether they run successfully or fail to compile. Given how popular it is in the ecosystem, and how easy it would be to support it, I think it makes sense to introduce some logic to handle this correctly. This PR adds support for `trybuild` and a few other crates in the category:

- `target/tests/target` for `kaos` and `macrotest`;
- `target/tests/trybuild` for `trybuild`.

As far as I know `tests` is not used by any other popular crates, so there should be no conflicts. These are quite ordinary nested target directories and the code changes are trivial. I might need some help with the testing, though – not sure how the current setup works. I'm allowing edits by maintainers so you can push directly to this branch, if you so prefer, I don't mind.

Relevant issues in other repositories:
- https://github.com/solana-labs/solana/pull/10826
- https://github.com/Sovereign-Labs/sovereign-sdk/issues/735 (that's me!)

Thank you so much for the action, by the way! I use it a bunch :smile:

### CODE REVIEW

**Comment by neysofu** [comment]
Hi @Swatinem, let me know if I can assist with the review in any way! 😄

**Review by Swatinem — APPROVED** [review]
I believe that should do the trick.
There isn’t really a lot of testing going on with `rust-cache` except running various `cargo test` variants to see if things are properly cached or not.

**Comment by neysofu** [comment]
Thanks for the review! I had to fix CI (forgot to run `npm run prepare`), should pass now.

**Comment by Swatinem** [comment]
However the caching does not fully work I believe:
https://github.com/Swatinem/rust-cache/actions/runs/6162180271/job/16723178553?pr=168
This is still compiling the world as part of the trybuild test.

**Comment by neysofu** [comment]
I suspect it's because the first run didn't include the changes to `dist/`, so it deleted `tests/trybuild` resulting in a rebuild.

Can we try deleting the cache and doing 2 runs of `simple.yml` (one uncached and the other hopefully cached)? If we still see a re-build then yeah, we have a problem.

**Comment by Swatinem** [comment]
Oh yeah indeed, that would explain it.

Let me delete the cache and rerun this as you suggested.

**Comment by Swatinem** [comment]
Works like a charm, thanks!

**Pull request merged**
