### PR TITLE
chore: use 8 character hash components

### LINKED ISSUE #97: Reduce key length?
Thanks for the excellent action! We use it lots in PRQL.

One very minor thing — I'm occasionally trying to understand where & why a key changed. The current keys are very long, and I _think_ would serve the same purpose being just a few characters long.

Here's an example, from https://github.com/PRQL/prql/actions/caches — it's possible but not easy to see which use different keys:

image

### PR DESCRIPTION
**Pull request by stevenh**
Use 8 character hash components to reduce the key length, making it more readable.

Fixes #97

### CODE REVIEW

**Comment by stevenh** [comment]
This is stacked on top of #142

**Review by Swatinem — COMMENTED** [review]
I would just always truncate this to 8 chars (aka 4 bytes of hash value) instead of making it configurable.

This is not supposed to be a cryptographic hash, even in the unlikely case of a 1-in-4-billion collision, the worst thing that can happen is that the build is taking a longer time because it does not have the right artifacts. So what 🤷🏻‍♂️

**Comment by stevenh** [comment]
> I would just always truncate this to 8 chars (aka 4 bytes of hash value) instead of making it configurable.
> 
> This is not supposed to be a cryptographic hash, even in the unlikely case of a 1-in-4-billion collision, the worst thing that can happen is that the build is taking a longer time because it does not have the right artifacts. So what 🤷🏻‍♂️

The reason I made it configurable was to keep compatible with existing caches. Yes this would be one time change when it pulls the new version and for small projects the impact wouldn't be to bad, but for large projects it could cause noticeable delays.

As this is more a quality of file change and all other caches use the full hash, felt like keeping the standard hash as the default would be the best course. Thoughts?

**Comment by Swatinem** [comment]
> for small projects the impact wouldn't be to bad, but for large projects it could cause noticeable delays

A cache by definition is best-effort. There is never a guarantee, just a hit-rate to optimize for, so a full rebuild every once in a while does not hurt. :-)

**Comment by stevenh** [comment]
Will update this once we have the key stability PR landed😊

**Review by Swatinem — APPROVED** [review]

**Comment by max-sixty** [comment]
Thanks @stevenh !

**Pull request merged**
