### PR TITLE
Update workspaces docs

### PR DESCRIPTION
**Pull request by thomaseizinger**
I did not have any success with the specified syntax and after checking the [example](https://github.com/Swatinem/rust-cache/blob/master/.github/workflows/workspaces.yml), it seems like the docs are outdated here.

### CODE REVIEW

**Comment by Swatinem** [comment]
This should be working as documented. If it does not, thats rather a bug.

**Comment by thomaseizinger** [comment]
> This should be working as documented. If it does not, thats rather a bug.

Okay, thanks for commenting. I can't seem to get my usecase working anyway so I am using the bare cache action now.

If this should be working as documented I'll close here.

**Comment by Swatinem** [comment]
> I can't seem to get my usecase working

Can you describe it or point to a run that does not work as intended?

**Comment by thomaseizinger** [comment]
> > I can't seem to get my usecase working
> 
> Can you describe it or point to a run that does not work as intended?

I tried to cache stuff from `cargo semver-checks`. It builds the local repo under `target/semver-checks/target`.

I tried to set `target/semver-checks` as a workspace but then it doesn't consider the lockfiles.

If I add the local dir as a workspace, the `semver-checks` directory gets "cleaned" before it gets cached because it is inside the other `target` directory.

I mostly wanted the auto-cleaning functionality. I can report back when I have something working that I am happy with!

**Pull request closed without merging**
